### PR TITLE
Adding components folder with Q&A.jsx file inside

### PR DESCRIPTION
**Pull request by agonzalezengr**
testing this stuff

### CODE REVIEW

**Comment by RichiV24** [comment]
Nice!

**Review by vickiwong85 — COMMENTED** [review]
Awesome Sauce

**Review by vickiwong85 — APPROVED** [review]

**Review by kjmoyer — APPROVED** [review]
Approved!

**Review by RichiV24 — CHANGES_REQUESTED** [review]
BAD CODE SPOTTED

**Pull request merged**
